# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OSS/BSS Education
email: oss.bss.education@ericsson.com
description: > # this means to ignore newlines until "baseurl:"
  We are the Ericsson OSS BSS eLearning team, a multidisciplinary group if eLearning experts with skills in education, technology, project management and web development.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
